
var data=[{'tipo':'Mexicana',
           'nombre':'Restaurante Méxicano',
           'zona':'Centro',
           'direccion':'metro Insurgentes',
           'rango':'$$$',
           'imagen':'assets/images/mexicana.jpg',
           'domicilio':true
          },
          {'tipo':'Mexicana',
            'nombre':'Restaurante Méxicano',
            'zona':'Centro',
            'direccion':'metro Insurgentes',
            'rango':'$$$',
            'imagen':'assets/images/mexicana2.jpg',
            'domicilio':true
          },
          {'tipo':'Mexicana',
           'nombre':'Restaurante Méxicano',
           'zona':'Centro',
           'direccion':'metro Insurgentes',
           'rango':'$$$',
           'imagen':'assets/images/mexicana3.jpg',
           'domicilio':true
          },
          {'tipo':'Mexicana',
           'nombre':'Restaurante Méxicano',
           'zona':'Centro',
           'direccion':'metro Insurgentes',
           'rango':'$$$',
           'imagen':'assets/images/mexicana4.jpg',
           'domicilio':true
          },
          {'tipo':'Mexicana',
           'nombre':'Restaurante Méxicano',
           'zona':'Centro',
           'direccion':'metro Insurgentes',
           'rango':'$$$',
           'imagen':'assets/images/mexicana5.jpg',
           'domicilio':true
          },
          {'tipo':'Mexicana',
           'nombre':'Restaurante Méxicano',
           'zona':'Centro',
           'direccion':'metro Insurgentes',
           'rango':'$$$',
           'imagen':'assets/images/mexicana6.jpg',
           'domicilio':true
           },

          {'tipo':'Italiana',
            'nombre':'Restaurante Italiano',
            'zona':'Sur',
            'direccion':'Periferico Sur',
            'rango':'$$$$',
            'imagen':'assets/images/italiana.jpg',
            'domicilio':false
          },
          {'tipo':'Italiana',
           'nombre':'Restaurante Italiano',
           'zona':'Sur',
           'direccion':'Periferico Sur',
           'rango':'$$$$',
           'imagen':'assets/images/italiana2.jpg',
           'domicilio':false
          },
          {'tipo':'Italiana',
           'nombre':'Restaurante Italiano',
           'zona':'Sur',
           'direccion':'Periferico Sur',
           'rango':'$$$$',
           'imagen':'assets/images/italiana3.jpg',
           'domicilio':false
           },
           {'tipo':'Italiana',
            'nombre':'Restaurante Italiano',
            'zona':'Sur',
            'direccion':'Periferico Sur',
            'rango':'$$$$',
            'imagen':'assets/images/italiana4.jpg',
            'domicilio':false
           },
           {'tipo':'Italiana',
            'nombre':'Restaurante Italiano',
            'zona':'Sur',
            'direccion':'Periferico Sur',
            'rango':'$$$$',
            'imagen':'assets/images/italiana5.jpg',
            'domicilio':false
           },
           {'tipo':'Italiana',
            'nombre':'Restaurante Italiano',
            'zona':'Sur',
            'direccion':'Periferico Sur',
            'rango':'$$$$',
            'imagen':'assets/images/italiana6.jpg',
            'domicilio':false
           },
           { 'tipo':'China',
              'nombre':'Restaurante Chino',
              'zona':'Norte',
              'direccion':'Indios Verdes',
              'rango':'$$',
              'imagen':'assets/images/china.jpg',
              'domicilio':true
             }]
