
var data=[{'tipo':'Mexicana',
           'nombre':'Restaurante Méxicano',
           'zona':'Centro',
           'direccion':'metro Insurgentes',
           'rango':'$$$',
           'imagen':'assets/images/mexicana.jpg',
           'domicilio':true
          },
          {'tipo':'Mexicana',
            'nombre':'Restaurante Méxicano',
            'zona':'Centro',
            'direccion':'metro Insurgentes',
            'rango':'$$$',
            'imagen':'assets/images/mexicana2.jpg',
            'domicilio':true
          },
          {'tipo':'Mexicana',
           'nombre':'Restaurante Méxicano',
           'zona':'Centro',
           'direccion':'metro Insurgentes',
           'rango':'$$$',
           'imagen':'assets/images/mexicana3.jpg',
           'domicilio':true
          },
          {'tipo':'Mexicana',
           'nombre':'Restaurante Méxicano',
           'zona':'Centro',
           'direccion':'metro Insurgentes',
           'rango':'$$$',
           'imagen':'assets/images/mexicana4.jpg',
           'domicilio':true
          },
          {'tipo':'Mexicana',
           'nombre':'Restaurante Méxicano',
           'zona':'Centro',
           'direccion':'metro Insurgentes',
           'rango':'$$$',
           'imagen':'assets/images/mexicana5.jpg',
           'domicilio':true
          },
          {'tipo':'Mexicana',
           'nombre':'Restaurante Méxicano',
           'zona':'Centro',
           'direccion':'metro Insurgentes',
           'rango':'$$$',
           'imagen':'assets/images/mexicana6.jpg',
           'domicilio':true
           },

          {'tipo':'Italiana',
             'nombre':'Restaurante Italiano',
             'zona':'Sur',
             'direccion':'Periferico Sur',
             'rango':'$$$$',
             'imagen':'http://dummyimage.com/162x148.png/ff4444/ffffff',
             'domicilio':false
           },
           { 'tipo':'China',
              'nombre':'Restaurante Chino',
              'zona':'Norte',
              'direccion':'Indios Verdes',
              'rango':'$$',
              'imagen':'http://dummyimage.com/162x148.png/ff4444/ffffff',
              'domicilio':true
             }]
